<a href="https://colab.research.google.com/github/kholikulovelyor/Data-Darsliklari-uchun/blob/main/2_1_3_Arr_Or_Pr_4Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Data Science Praktikum**
> Data Science va Sun'iy Intellekt Praktikum

> Ma'lumotlar tahlili

2.1. Numpy kutubxonasi bilan ishlash 


In [ ]:
import numpy as np

2.1.3. Massivga yo'naltirilgan dasturlash 

#**Tartiblash**
 `Sorting`

In [ ]:
# data
arr = np.random.rand(4) # 4 ta taxminiy elementlardan tashkil topgan massiv
arr

array([0.75038727, 0.03475834, 0.1174923 , 0.98178248])

#**Sort**
>`Sort` funksiyasi 

In [ ]:
# 1 usul
sorted_arr = np.sort(arr) # arr massivini tartiblangan ko'rinishini sorted_arr joylaydi
sorted_arr

array([0.03475834, 0.1174923 , 0.75038727, 0.98178248])

In [17]:
# 2 usul 
sorted_arr.sort() # arr ning tartiblangan ko'rinishi
sorted_arr

array([0.03475834, 0.1174923 , 0.75038727, 0.98178248])

#Teskari tartiblash



In [22]:
rev_arr = -np.sort(-arr) # teskari tartibdagi arr
rev_arr

array([0.98178248, 0.75038727, 0.1174923 , 0.03475834])

In [35]:
# 2 D array (massiv)
arr2d = np.random.randn(2, 4) # (2, 4) random massiv
arr2d

array([[ 1.8030505 ,  1.38519883,  1.12000362,  1.40983625],
       [-0.16860593, -1.35920359, -0.13813715,  0.52773212]])

In [36]:
# axis = 0 -- Qator o'qi
# axis = 1 -- ustun o'qi

In [37]:
row_srt = np.sort(arr2d, axis=0) # arr2d ning xar bir qator bo'yicha tartiblangan ko'rinishi
row_srt

array([[-0.16860593, -1.35920359, -0.13813715,  0.52773212],
       [ 1.8030505 ,  1.38519883,  1.12000362,  1.40983625]])

In [41]:
# Axis = 1 --> Ustun o'qi
col_srt = np.sort(arr2d, axis=1) # arr2d ning xar bir ustun bo'yicha tartiblangan ko'rinishi
col_srt

array([[ 1.12000362,  1.38519883,  1.40983625,  1.8030505 ],
       [-1.35920359, -0.16860593, -0.13813715,  0.52773212]])