<a href="https://colab.research.google.com/github/kholikulovelyor/Data-Darsliklari-uchun/blob/main/2_1_3_Arr_Or_Pr_1_Math%26Stat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Mohirdev**
#Data Science va Suniy intellekt Praktikum
#Ma'lumotlar tahlili
#Mavzu: Matematik va Statistik amallar.

In [3]:
import numpy as np

2.1.3 Massivga yo'naltirilgan dasturlash

Matematik Statistik amallar qo'llash

In [4]:
#data
arr = np.random.randn(5,4)  # (5, 4) o'lchovli massiv (random)
arr 

array([[-0.28457325,  1.34455078, -0.66999342,  0.88903879],
       [-0.23373448, -0.78941381, -1.03809739,  0.09464545],
       [-0.60161741, -1.65311075,  0.6122492 ,  2.17717428],
       [ 1.76375579, -0.1398543 , -1.38678613, -0.65088361],
       [ 0.35352491, -1.87168229,  0.9739133 ,  1.07778745]])

#**`sum` methodi**
#Tavsif

English:
>The Python *sum*() function calculates the total of all numerical values in an 
iterable. sum() works with both integers and floating-point numbers. The sum() function has an optional parameter to add a number to the total. alculating the sum of a list is a common operation in Python

Uzbek:
>Barcha elementlarni yig'indisini hisoblaydi

ikkita bir xil usul

In [5]:
arr.sum() # arr ning barcha elementlarni yig'indisini hisoblab beradi

-0.03310689943672718

In [5]:
np.sum(arr) # arr ning barcha elementlarni yig'indisini hisoblab beradi

In [7]:
arr

array([[-0.28457325,  1.34455078, -0.66999342,  0.88903879],
       [-0.23373448, -0.78941381, -1.03809739,  0.09464545],
       [-0.60161741, -1.65311075,  0.6122492 ,  2.17717428],
       [ 1.76375579, -0.1398543 , -1.38678613, -0.65088361],
       [ 0.35352491, -1.87168229,  0.9739133 ,  1.07778745]])

In [8]:
arr.sum(axis=1) # qator yi'gindi
#Axis meaning in uzbek language (o'qi)


array([ 1.27902291, -1.96660022,  0.53469531, -0.41376826,  0.53354337])

In [9]:
arr.sum(axis=0) # ustun yi'gindi

array([ 0.99735556, -3.10951038, -1.50871445,  3.58776237])

#**mean methodi**
#Tavsif

English
>mean() function can be used to calculate mean/average of a given list of numbers. It returns mean of the data set passed as parameters. Arithmetic mean is the sum of data divided by the number of data-points. It is a measure of the central location of data in a set of values which vary in range

Uzbek
>Barcha elemtlarning yig'indisini o'sha elemtlarning soniga  nisbati.




In [15]:
# Sodda Ma'lumot 
data = np.arange(11) # 0 ~ 5 gacha bo'lgan elementlarda tashkil topgan massiv
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
mean = np.sum(data)/len(data)
mean

5.0

In [17]:
#ikkinchi usuli 
np.mean(data)

5.0

In [16]:
data.mean()

5.0

In [19]:
arr

array([[-0.28457325,  1.34455078, -0.66999342,  0.88903879],
       [-0.23373448, -0.78941381, -1.03809739,  0.09464545],
       [-0.60161741, -1.65311075,  0.6122492 ,  2.17717428],
       [ 1.76375579, -0.1398543 , -1.38678613, -0.65088361],
       [ 0.35352491, -1.87168229,  0.9739133 ,  1.07778745]])

In [25]:
np.mean(arr)  # arr ning o'rtacha qiymati

-0.0016553449718363588

In [26]:
np.mean(arr, axis=1) # qator bo'yich o'rtacha qiymatni qaytaradi

array([ 0.31975573, -0.49165006,  0.13367383, -0.10344206,  0.13338584])

In [27]:
np.mean(arr, axis=0) # ustunlar bo'yicha o'rtacha qiymatni qaytaradi

array([ 0.19947111, -0.62190208, -0.30174289,  0.71755247])

#**`Cumsum` methodi**
#Tavsif

English:
>Python numpy cumsum() function returns the cumulative sum of the elements along the given axis.

Uzbek:
>Barcha yig'indilarni hisobga olib boradigan yig'indi



In [28]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
data.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [30]:
np.cumsum(data)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55])