<a href="https://colab.research.google.com/github/kholikulovelyor/Data-Darsliklari-uchun/blob/main/_5_transposing%26Swapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Data Science va Sun`iy intellekt praktikum**

Ma`lumotlar tahlili
2.1. Numpy kutubxonasi bilan ishlash

In [ ]:
import numpy as np

2.1.1. N-O'lchamli massiv(array)larga ishlov berish.
Massivlarning pozitsiyasini ko'chirish va `Transpose` va o'qlar o'rnini almashtirish `Swapping axes`

#reshape methodi 

In [ ]:
A = np.arange(6).reshape(3, 2) # A massiv: Elemtlari 0-6 gacha, shape (3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

#`Transpose`

In [ ]:
A.T # A massivning Transpose ko`rinishini beradi 

array([[0, 2, 4],
       [1, 3, 5]])

#`Swapping axes`

In [ ]:
A.swapaxes(1, 0) # A massivning Transpose ko'rinishi beradi 

array([[0, 2, 4],
       [1, 3, 5]])

#Transposening ishlatilinishiga bir misol AA^T








In [ ]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
np.dot(A, A.T) # AA^T hosil bo'lgan massiv 

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])