<a href="https://colab.research.google.com/github/kholikulovelyor/Data-Darsliklari-uchun/blob/2-modul-Data-Analysis-Numpy-kutubxonasi/Chiziqli_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Data Science va Sun'iy Itellekt Praktikum**
Malumotlar tahlili. Numpy kutubxonasi

Chiziqli Algebra

In [19]:
import numpy as np

In [24]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

NumPy va Chiziqli Algebra haqida yaxshi maqola:[Maqola](https://towardsdatascience.com/introduction-to-linear-algebra-with-numpy-79adeb7bc060)

In [21]:
y = np.array([[5., 5., 5.], [4., 4., 4.]])
y

array([[5., 5., 5.],
       [4., 4., 4.]])

In [26]:
x+y # matritsani bir biriga qo'shish

array([[ 6.,  7.,  8.],
       [ 8.,  9., 10.]])

In [28]:
y-x # matritsani ayirish

array([[ 4.,  3.,  2.],
       [ 0., -1., -2.]])

In [31]:
x*5 # skalyar ko'paytirish ya'ni 5 arrayni har bir elementiga ko'paytiriladi
y*5

array([[25., 25., 25.],
       [20., 20., 20.]])

In [32]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [35]:
y1 = np.array([[6., 23.], [1., -7.], [8., 9.]])

In [36]:
y1

array([[ 6., 23.],
       [ 1., -7.],
       [ 8.,  9.]])

In [38]:
x.dot(y1) # x*y natijasini beradi

array([[ 32.,  36.],
       [ 77., 111.]])

Tepadagi methodni boshqa usuli

In [40]:
np.dot(x,y1)

array([[ 32.,  36.],
       [ 77., 111.]])

In [43]:
y1.dot(x) # 3*3 matritsa hosil bo'ldi

array([[ 98., 127., 156.],
       [-27., -33., -39.],
       [ 44.,  61.,  78.]])

In [45]:
# Linear Algebra 
from numpy.linalg import inv