<a href="https://colab.research.google.com/github/kholikulovelyor/Data-Darsliklari-uchun/blob/2-modul-Data-Analysis-Numpy-kutubxonasi/fayllar_bilan_ishlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Data Science va Sun'iy Intellekt Praktikum**
Ma'lumotlar tahlili va numpy kutubxonasi
Fayllar bilan ishlash



In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Faylni saqlash usuli

In [ ]:
np.save('data', arr)

faylni yuklash usuli

In [ ]:
arr2 = np.load('data.npy')

In [ ]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1 = np.arange(20)

Bir nechta arraylarni bitta faylga joylash 

In [ ]:
np.savez('arrays', a = arr, b=arr1)

tepadgi faylni o'qish ucun bu usuldan foydalanamiz

In [ ]:
arrays = np.load('arrays.npz')
arrays

Shu usul bilan murojat qilamiz


In [ ]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Bu usul yuqoridagi usullar bilan bir xil faqat bu arraylarni siqilgan formatda saqlaydi

In [ ]:
np.savez_compressed(arrays)